alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

name: geheim
region: fra
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: blemli/geheim
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  name: geheim
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm app:app
  source_dir: /